// ============================================================
// super-ai.js — CUT-REAL AI SUPER
// Módulo aislado. No modifica Chat Mode, Agent Mode ni Sandbox.
// Las claves nunca se guardan en este archivo, localStorage o HTML.
// ============================================================
(function () {
  'use strict';

  const STORAGE_CONFIG = 'cutreal_super_config_v1';
  const STORAGE_HISTORY = 'cutreal_super_history_v1';
  const MAX_NODES = 12;
  const $ = id => document.getElementById(id);
  const esc = value => String(value == null ? '' : value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
  const uid = prefix => `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 7)}`;
  const clamp = (value, min, max) => Math.min(max, Math.max(min, Number(value) || min));

  const defaultNodes = [
    { id: uid('ai'), role: 'PRIMARY ANALYST', provider: 'openai', model: 'gpt-4o-mini', keyId: 'super-openai-1', enabled: true },
    { id: uid('ai'), role: 'CRITICAL REVIEWER', provider: 'gemini', model: 'gemini-2.0-flash', keyId: 'super-gemini-1', enabled: true },
    { id: uid('ai'), role: 'EDITOR / SYNTHESIZER', provider: 'groq', model: 'llama-3.3-70b-versatile', keyId: 'super-groq-1', enabled: true },
  ];
  const state = {
    open: false, running: false, paused: false, cancelled: false, selectedNodeId: null,
    mode: 'sequential', rounds: 1, maxTokens: 900, maxTokensTotal: 14000, maxRetries: 1, maxBudget: '', fallbackEnabled: true,
    nodes: defaultNodes, providers: [], result: null, history: [], timeline: [], abortController: null,
    mapScale: 1, mapPanX: 0, mapPanY: 0, pointer: null, replayTimer: null,
  };

  function readJSON(key, fallback) { try { return JSON.parse(localStorage.getItem(key) || 'null') || fallback; } catch (_) { return fallback; } }
  function saveJSON(key, value) { try { localStorage.setItem(key, JSON.stringify(value)); } catch (_) {} }
  function loadConfig() {
    const saved = readJSON(STORAGE_CONFIG, null);
    if (!saved) return;
    state.mode = ['sequential', 'parallel', 'hybrid'].includes(saved.mode) ? saved.mode : state.mode;
    state.rounds = clamp(saved.rounds, 1, 5); state.maxTokens = clamp(saved.maxTokens, 128, 3000); state.maxTokensTotal = clamp(saved.maxTokensTotal, 1000, 50000); state.maxRetries = clamp(saved.maxRetries, 0, 3); state.maxBudget = saved.maxBudget ?? ''; state.fallbackEnabled = saved.fallbackEnabled !== false;
    if (Array.isArray(saved.nodes) && saved.nodes.length) state.nodes = saved.nodes.slice(0, MAX_NODES).map(node => ({ ...node, id: node.id || uid('ai'), enabled: node.enabled !== false }));
  }
  function saveConfig() { saveJSON(STORAGE_CONFIG, { mode: state.mode, rounds: state.rounds, maxTokens: state.maxTokens, maxTokensTotal: state.maxTokensTotal, maxRetries: state.maxRetries, maxBudget: state.maxBudget, fallbackEnabled: state.fallbackEnabled, nodes: state.nodes }); }
  function loadHistory() { const saved = readJSON(STORAGE_HISTORY, []); state.history = Array.isArray(saved) ? saved.slice(0, 30) : []; }
  function saveHistory() { saveJSON(STORAGE_HISTORY, state.history.slice(0, 30)); }

  function notify(text, color) { if (typeof window.showToast === 'function') window.showToast(text, color || '#52e8d0', '⚡'); }
  function setOpen(open) {
    state.open = Boolean(open); const view = $('super-view'); if (!view) return;
    view.hidden = !state.open; view.setAttribute('aria-hidden', String(!state.open));
    document.body.classList.toggle('super-view-active', state.open);
    if (state.open) { loadConfig(); loadHistory(); renderAll(); loadProviders(); setTimeout(resizeMap, 40); }
  }
  function open() { setOpen(true); }
  function close() { if (state.running) { notify('La sesión SUPER sigue activa; cancelala antes de salir.', '#ffae62'); return; } setOpen(false); }

  function providerLabel(provider) { return String(provider || '').toUpperCase(); }
  function renderProviders() {
    const list = $('super-provider-list'); if (!list) return;
    if (!state.providers.length) { list.innerHTML = '<div class="super-empty">No hay claves SUPER configuradas en el backend. Configurá SUPER_AI_KEYS_JSON o SUPER_AI_* en Vercel.</div>'; return; }
    list.innerHTML = state.providers.map(item => `<div class="super-provider-row"><span class="super-health super-health-${item.enabled ? 'online' : 'offline'}">${item.enabled ? 'ONLINE' : 'OFFLINE'}</span><strong>${esc(providerLabel(item.provider))}</strong><span>${esc(item.model)}</span><span class="super-key-mask">${esc(item.maskedKey)}</span><small>${esc(item.displayName)}</small></div>`).join('');
  }
  async function loadProviders() {
    try { const res = await fetch('/api/super-ai', { headers: { Accept: 'application/json' } }); const data = await res.json(); state.providers = Array.isArray(data.providers) ? data.providers : []; renderProviders(); renderNodeEditor(); } catch (error) { state.providers = []; renderProviders(); }
  }
  async function testConnection() {
    const provider = $('super-test-provider')?.value; const model = $('super-test-model')?.value.trim(); const apiKey = $('super-test-key')?.value || '';
    const output = $('super-test-output'); if (!provider || !model || !apiKey) { if (output) output.textContent = 'Ingresá proveedor, modelo y clave solo para probarla. No se guardará.'; return; }
    if (output) output.textContent = 'TESTING CONNECTION…';
    try { const res = await fetch('/api/super-ai', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'test-connection', provider, model, apiKey }) }); const data = await res.json(); if (output) output.textContent = data.ok ? `✓ ${data.message} · ${data.provider}/${data.model}` : `✗ ${data.type || 'ERROR'} · ${data.error || 'falló la conexión'}`; } catch (error) { if (output) output.textContent = `✗ NETWORK ERROR · ${error.message}`; }
    const field = $('super-test-key'); if (field) field.value = '';
  }

  function addNode() { if (state.nodes.length >= MAX_NODES) return notify(`Máximo de ${MAX_NODES} modelos en esta interfaz.`, '#ffae62'); const index = state.nodes.length + 1; state.nodes.push({ id: uid('ai'), role: `AI ${String(index).padStart(2, '0')}`, provider: state.providers[0]?.provider || 'openai', model: state.providers[0]?.model || 'gpt-4o-mini', keyId: state.providers[0]?.id || '', enabled: true }); saveConfig(); renderAll(); }
  function removeNode(id) { if (state.nodes.length <= 2) return notify('SUPER necesita al menos 2 modelos habilitados.', '#ffae62'); state.nodes = state.nodes.filter(node => node.id !== id); saveConfig(); renderAll(); }
  function moveNode(id, direction) { const index = state.nodes.findIndex(node => node.id === id); const next = index + direction; if (index < 0 || next < 0 || next >= state.nodes.length) return; [state.nodes[index], state.nodes[next]] = [state.nodes[next], state.nodes[index]]; saveConfig(); renderAll(); }
  function updateNode(id, patch) { const node = state.nodes.find(item => item.id === id); if (!node) return; Object.assign(node, patch); saveConfig(); renderPipeline(); }

  function renderNodeEditor() {
    const el = $('super-node-editor'); if (!el) return;
    const providerOptions = ['openai', 'gemini', 'groq', 'xai', 'mistral', 'deepseek', 'openrouter'];
    el.innerHTML = state.nodes.map((node, index) => `<div class="super-node-config" data-super-node="${esc(node.id)}"><div class="super-node-order">${String(index + 1).padStart(2, '0')}</div><div class="super-node-fields"><label>Rol<input data-field="role" value="${esc(node.role)}" maxlength="80"></label><label>Proveedor<select data-field="provider">${providerOptions.map(provider => `<option value="${provider}" ${provider === node.provider ? 'selected' : ''}>${providerLabel(provider)}</option>`).join('')}</select></label><label>Modelo<input data-field="model" value="${esc(node.model)}" maxlength="150" placeholder="modelo configurado"></label><label>SUPER key ID<input data-field="keyId" value="${esc(node.keyId)}" maxlength="80" placeholder="ID backend"></label></div><div class="super-node-actions"><button data-move="-1" title="Mover arriba">↑</button><button data-move="1" title="Mover abajo">↓</button><button data-remove="1" title="Quitar modelo">−</button></div></div>`).join('');
    el.querySelectorAll('.super-node-config').forEach(row => row.querySelectorAll('[data-field]').forEach(field => field.addEventListener('change', () => updateNode(row.dataset.superNode, { [field.dataset.field]: field.value }))));
    el.querySelectorAll('[data-move]').forEach(button => button.addEventListener('click', () => moveNode(button.closest('.super-node-config').dataset.superNode, Number(button.dataset.move))));
    el.querySelectorAll('[data-remove]').forEach(button => button.addEventListener('click', () => removeNode(button.closest('.super-node-config').dataset.superNode)));
  }

  function stateClass(status) { return String(status || 'waiting').toLowerCase().replace(/[^a-z_]/g, '_'); }
  function statusLabel(status) { return ({ waiting: '○ WAITING', processing: '🔵 PROCESSING', completed: '🟢 COMPLETED', error: '🔴 ERROR', retrying: '🟠 RETRYING', skipped: '⚪ SKIPPED', paused: '🟡 PAUSED' }[status] || '○ WAITING'); }
  function nodeStatus(nodeId) { const events = state.timeline.filter(event => event.nodeId === nodeId); return events.at(-1)?.status || 'waiting'; }
  function drawMap() {
    const canvas = $('super-map-canvas'); if (!canvas) return; const ctx = canvas.getContext('2d'); const dpr = window.devicePixelRatio || 1; const width = canvas.clientWidth || 640; const height = canvas.clientHeight || 500; if (canvas.width !== width * dpr || canvas.height !== height * dpr) { canvas.width = width * dpr; canvas.height = height * dpr; } ctx.setTransform(dpr, 0, 0, dpr, 0, 0); ctx.clearRect(0, 0, width, height); ctx.fillStyle = '#050b15'; ctx.fillRect(0, 0, width, height); ctx.save(); ctx.translate(width / 2 + state.mapPanX, 45 + state.mapPanY); ctx.scale(state.mapScale, state.mapScale); const nodes = state.nodes.filter(node => node.enabled); const vertical = width < 700; const spacingX = 190; const spacingY = 112; const positions = new Map(); nodes.forEach((node, index) => { const x = vertical ? 0 : (index - (nodes.length - 1) / 2) * spacingX; const y = vertical ? index * spacingY : 120 + (index % 2) * 18; positions.set(node.id, { x, y }); }); const finalY = vertical ? nodes.length * spacingY + 28 : 285; const first = nodes[0]; if (first) { const p = positions.get(first.id); ctx.strokeStyle = '#4bd8e8aa'; ctx.lineWidth = 2; nodes.slice(1).forEach(node => { const q = positions.get(node.id); ctx.beginPath(); ctx.moveTo(p.x, p.y + 28); ctx.lineTo(q.x, q.y + 28); ctx.stroke(); }); nodes.forEach(node => { const p = positions.get(node.id); ctx.strokeStyle = nodeStatus(node.id) === 'completed' ? '#54e6b0' : nodeStatus(node.id) === 'error' ? '#ff6c83' : '#4bd8e8'; ctx.beginPath(); ctx.moveTo(p.x, p.y + 28); ctx.lineTo(0, finalY); ctx.stroke(); }); }
    ctx.strokeStyle = '#b875ff'; ctx.beginPath(); ctx.moveTo(0, finalY); ctx.lineTo(0, finalY + 55); ctx.stroke(); ctx.fillStyle = '#0d1a29'; ctx.strokeStyle = '#b875ff'; ctx.lineWidth = 1.5; ctx.beginPath(); ctx.roundRect(-90, finalY + 55, 180, 58, 12); ctx.fill(); ctx.stroke(); ctx.fillStyle = '#e4ccff'; ctx.font = 'bold 12px ui-monospace,monospace'; ctx.textAlign = 'center'; ctx.fillText('FINAL SYNTHESIS', 0, finalY + 81); ctx.fillStyle = '#9f89b4'; ctx.font = '10px ui-monospace,monospace'; ctx.fillText(state.result ? 'RESULT READY' : 'WAITING', 0, finalY + 99); nodes.forEach(node => { const p = positions.get(node.id); const status = nodeStatus(node.id); const color = status === 'completed' ? '#54e6b0' : status === 'error' ? '#ff6c83' : status === 'processing' ? '#4bd8e8' : '#6d8191'; ctx.fillStyle = '#091523'; ctx.strokeStyle = state.selectedNodeId === node.id ? '#ffffff' : color; ctx.lineWidth = state.selectedNodeId === node.id ? 3 : 1.5; ctx.beginPath(); ctx.roundRect(p.x - 82, p.y - 7, 164, 70, 12); ctx.fill(); ctx.stroke(); ctx.fillStyle = color; ctx.textAlign = 'center'; ctx.font = 'bold 11px ui-monospace,monospace'; ctx.fillText(`AI ${String(nodes.indexOf(node) + 1).padStart(2, '0')} · ${String(node.role).slice(0, 18)}`, p.x, p.y + 15); ctx.fillStyle = '#b5c5cf'; ctx.font = '10px ui-monospace,monospace'; ctx.fillText(String(node.model || 'model').slice(0, 23), p.x, p.y + 31); ctx.fillStyle = color; ctx.fillText(statusLabel(status), p.x, p.y + 48); }); ctx.restore();
  }
  function resizeMap() { const canvas = $('super-map-canvas'); if (!canvas) return; drawMap(); }
  function renderPipeline() {
    const list = $('super-pipeline-nodes');
    if (!list) return;
    const nodes = state.nodes.filter(node => node.enabled);
    const html = nodes.map((node, index) => {
      const status = nodeStatus(node.id);
      const result = state.result?.steps?.flatMap(step => step.results || []).find(item => item.nodeId === node.id && item.status === 'completed');
      const meta = result ? `<span class="super-node-meta">${result.tokens ? `${result.tokens} tokens · ` : ''}${result.latencyMs || 0} ms</span>` : '';
      const arrow = index < nodes.length - 1 ? '<span class="super-pipeline-arrow">↓</span>' : '';
      return `<button class="super-pipeline-node super-state-${stateClass(status)} ${state.selectedNodeId === node.id ? 'selected' : ''}" data-super-select="${esc(node.id)}"><span class="super-pipeline-index">AI ${String(index + 1).padStart(2, '0')}</span><strong>${esc(node.role)}</strong><small>${esc(providerLabel(node.provider))} / ${esc(node.model || 'modelo')}</small><em>${statusLabel(status)}</em>${meta}</button>${arrow}`;
    }).join('');
    list.innerHTML = `${html}<span class="super-pipeline-arrow">↓</span><div class="super-synthesis-node">⌬ FINAL SYNTHESIS <small>Cut-real AI</small></div>`;
    list.querySelectorAll('[data-super-select]').forEach(button => button.addEventListener('click', () => {
      state.selectedNodeId = button.dataset.superSelect;
      renderPipeline(); renderInspector(); drawMap();
    }));
    drawMap();
  }
  function renderInspector() {
    const el = $('super-node-inspector'); if (!el) return; const node = state.nodes.find(item => item.id === state.selectedNodeId); if (!node) { el.innerHTML = '<div class="super-empty">Seleccioná un nodo para inspeccionar sus datos reales.</div>'; return; } const results = state.result?.steps?.flatMap(step => step.results || []).filter(item => item.nodeId === node.id) || []; const item = results.at(-1); el.innerHTML = `<strong>NODE INSPECTOR · ${esc(node.role)}</strong><dl><dt>MODEL</dt><dd>${esc(item?.model || node.model || 'no disponible')}</dd><dt>PROVIDER</dt><dd>${esc(item?.provider || node.provider || 'no disponible')}</dd><dt>ROLE</dt><dd>${esc(node.role)}</dd><dt>STATUS</dt><dd>${esc(statusLabel(item?.status || nodeStatus(node.id)))}</dd><dt>TOKENS</dt><dd>${item?.tokens ?? 'no informado'}</dd><dt>LATENCY</dt><dd>${item?.latencyMs != null ? `${item.latencyMs} ms` : 'no informado'}</dd></dl>${item?.text ? `<details open><summary>RESPONSE</summary><p>${esc(item.text)}</p></details>` : ''}${item?.error ? `<p class="super-error">${esc(item.error.message || item.error)}</p>` : ''}`; }
  function renderTimeline() { const el = $('super-timeline'); if (!el) return; el.innerHTML = state.timeline.length ? state.timeline.map(event => `<div class="super-timeline-event super-state-${stateClass(event.status)}"><time>${new Date(event.at || Date.now()).toLocaleTimeString('es-AR')}</time><strong>${esc(event.type)}</strong><span>${esc(event.nodeId || 'PIPELINE')} ${event.tokens ? `· ${event.tokens} tokens` : ''}</span></div>`).join('') : '<div class="super-empty">La timeline aparecerá cuando exista actividad real del pipeline.</div>'; }
  function renderOutput() { const output = $('super-final-answer'); if (!output) return; if (!state.result) { output.innerHTML = '<span class="super-placeholder">La síntesis final aparecerá aquí después de una colaboración real.</span>'; return; } output.innerHTML = `<div class="super-result-badges"><span>${esc(state.result.consensus || 'Qualitative consensus')}</span><span>${state.result.metrics?.totalTokens || 0} tokens</span><span>${state.result.metrics?.durationMs || 0} ms</span></div><p>${esc(state.result.final)}</p><div class="super-warnings">${(state.result.warnings || []).map(warning => `<small>i ${esc(warning)}</small>`).join('')}</div>`; }
  function renderHistory() { const el = $('super-history-list'); if (!el) return; el.innerHTML = state.history.length ? state.history.map((item, index) => `<div class="super-history-item"><button data-super-history="${index}"><strong>${esc(item.question)}</strong><small>${new Date(item.at).toLocaleString('es-AR')} · ${esc(item.mode)} · ${item.finalOnly ? 'final' : 'proceso completo'}</small></button><button class="super-history-delete" data-super-delete="${index}" title="Eliminar sesión" aria-label="Eliminar sesión">×</button></div>`).join('') : '<div class="super-empty">No hay sesiones guardadas.</div>'; el.querySelectorAll('[data-super-history]').forEach(button => button.addEventListener('click', () => openHistory(Number(button.dataset.superHistory)))); el.querySelectorAll('[data-super-delete]').forEach(button => button.addEventListener('click', event => { event.stopPropagation(); deleteHistory(Number(button.dataset.superDelete)); })); }
  function renderAll() { renderProviders(); renderNodeEditor(); renderPipeline(); renderInspector(); renderTimeline(); renderOutput(); renderHistory(); const mode = $('super-mode'); if (mode) mode.value = state.mode; const rounds = $('super-rounds'); if (rounds) rounds.value = String(state.rounds); const maxTokens = $('super-max-tokens'); if (maxTokens) maxTokens.value = String(state.maxTokens); const total = $('super-max-total-tokens'); if (total) total.value = String(state.maxTokensTotal); const retries = $('super-max-retries'); if (retries) retries.value = String(state.maxRetries); const budget = $('super-budget'); if (budget) budget.value = state.maxBudget; const fallback = $('super-fallback'); if (fallback) fallback.checked = state.fallbackEnabled; const status = $('super-status'); if (status) status.textContent = state.running ? (state.paused ? 'PAUSED' : 'PROCESSING') : state.result ? 'COMPLETED' : 'READY'; }

  function appendEvent(event) { state.timeline.push(event); renderPipeline(); renderTimeline(); }
  function buildPayload() { const question = $('super-question')?.value.trim(); if (!question) throw new Error('Escribí una pregunta para SUPER.'); state.mode = $('super-mode')?.value || 'sequential'; state.rounds = clamp($('super-rounds')?.value, 1, 5); state.maxTokens = clamp($('super-max-tokens')?.value, 128, 3000); state.maxTokensTotal = clamp($('super-max-total-tokens')?.value, 1000, 50000); state.maxRetries = clamp($('super-max-retries')?.value, 0, 3); state.maxBudget = $('super-budget')?.value || ''; state.fallbackEnabled = $('super-fallback')?.checked !== false; saveConfig(); return { action: 'collaborate', question, nodes: state.nodes, mode: state.mode, rounds: state.rounds, maxTokens: state.maxTokens, maxTokensTotal: state.maxTokensTotal, maxRetries: state.maxRetries, maxBudget: state.maxBudget, fallbackEnabled: state.fallbackEnabled }; }
  async function runPipeline() { if (state.running) return; let payload; try { payload = buildPayload(); } catch (error) { notify(error.message, '#ff756f'); return; } state.running = true; state.paused = false; state.cancelled = false; state.result = null; state.timeline = []; state.abortController = new AbortController(); renderAll(); appendEvent({ type: 'USER_REQUEST', status: 'processing', at: Date.now() }); try { const response = await fetch('/api/super-ai', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload), signal: state.abortController.signal }); const data = await response.json(); if (!response.ok || !data.ok) throw new Error(data.error || 'SUPER no pudo completar la sesión.'); if (state.cancelled) return; state.result = data; state.timeline = Array.isArray(data.events) ? data.events : []; appendEvent({ type: 'FINAL_SYNTHESIS', status: 'completed', at: Date.now() }); renderAll(); notify('SUPER completó la síntesis con resultados reales.', '#54e6b0'); showConsent(); } catch (error) { if (error.name !== 'AbortError') { appendEvent({ type: 'PIPELINE_ERROR', status: 'error', error: error.message, at: Date.now() }); notify(error.message, '#ff756f'); } } finally { state.running = false; state.paused = false; state.abortController = null; renderAll(); } }
  function pausePipeline() { if (!state.running) return; state.paused = true; appendEvent({ type: 'PIPELINE_PAUSED', status: 'paused', at: Date.now() }); renderAll(); }
  function continuePipeline() { if (!state.running) return; state.paused = false; appendEvent({ type: 'PIPELINE_CONTINUED', status: 'processing', at: Date.now() }); renderAll(); }
  function cancelPipeline() { if (!state.running) return; state.cancelled = true; state.abortController?.abort(); appendEvent({ type: 'PIPELINE_CANCELLED', status: 'skipped', at: Date.now() }); state.running = false; renderAll(); }
  function skipSelected() { const node = state.nodes.find(item => item.id === state.selectedNodeId); if (!node || state.running) return notify('Seleccioná un nodo antes de iniciar una sesión para marcarlo como omitido.', '#ffae62'); node.enabled = false; saveConfig(); renderAll(); notify(`${node.role} quedará omitido en la próxima sesión.`, '#ffae62'); }

  function showConsent() { const box = $('super-consent'); if (box) box.hidden = false; }
  function hideConsent() { const box = $('super-consent'); if (box) box.hidden = true; }
  function saveSession(full) { if (!state.result) return; const item = { id: uid('session'), at: Date.now(), question: $('super-question')?.value.trim() || 'SUPER session', mode: state.mode, finalOnly: !full, final: state.result.final, consensus: state.result.consensus, metrics: state.result.metrics, result: full ? state.result : undefined }; state.history.unshift(item); state.history = state.history.slice(0, 30); saveHistory(); hideConsent(); renderHistory(); notify(full ? 'Proceso SUPER completo guardado.' : 'Solo la respuesta final fue guardada.', '#54e6b0'); }
  function deleteHistory(index) { state.history.splice(index, 1); saveHistory(); renderHistory(); }
  function openHistory(index) { const item = state.history[index]; if (!item) return; $('super-question').value = item.question; if (item.result) { state.result = item.result; state.timeline = item.result.events || []; } else { state.result = { final: item.final, consensus: item.consensus, metrics: item.metrics, warnings: ['Esta sesión se guardó como respuesta final solamente.'] }; state.timeline = []; } renderAll(); }
  function replayHistory() { const item = state.history.find(entry => entry.result); if (!item?.result) return notify('Guardá el proceso completo para reproducir sus eventos reales.', '#ffae62'); const events = item.result.events || []; let index = 0; state.timeline = []; state.result = null; renderAll(); clearInterval(state.replayTimer); state.replayTimer = setInterval(() => { if (index >= events.length) { clearInterval(state.replayTimer); state.result = item.result; renderAll(); return; } state.timeline.push(events[index]); index += 1; renderAll(); }, 380); }
  function exportProcess(format) { if (!state.result) return notify('No existe un resultado SUPER para exportar.', '#ffae62'); const title = $('super-question')?.value.trim() || 'CUT-REAL AI SUPER'; const text = [`CUT-REAL AI SUPER`, `Pregunta: ${title}`, `Modo: ${state.mode}`, `Consenso: ${state.result.consensus || 'Qualitative consensus'}`, '', `RESPUESTA FINAL`, state.result.final, '', 'MÉTRICAS', JSON.stringify(state.result.metrics || {}, null, 2), '', 'EVENTOS', ...(state.result.events || []).map(event => `${event.type} · ${event.nodeId || 'PIPELINE'} · ${event.status}`)].join('\n'); if (format === 'svg') { const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="800"><rect width="100%" height="100%" fill="#050b15"/><text x="40" y="60" fill="#74e8d0" font-family="monospace" font-size="24">CUT-REAL AI SUPER</text><foreignObject x="40" y="90" width="1120" height="660"><pre xmlns="http://www.w3.org/1999/xhtml" style="color:#d4e9ef;white-space:pre-wrap;font:14px monospace">${esc(text)}</pre></foreignObject></svg>`; downloadBlob(svg, 'cut-real-super-map.svg', 'image/svg+xml'); } else if (format === 'png') { const canvas = $('super-map-canvas'); if (canvas) { const link = document.createElement('a'); link.href = canvas.toDataURL('image/png'); link.download = 'cut-real-super-map.png'; link.click(); } } else downloadBlob(text, 'cut-real-super-process.txt', 'text/plain;charset=utf-8'); }
  function downloadBlob(content, name, type) { const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([content], { type })); link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 500); }

  function renderMapStatus() { const el = $('super-map-status'); if (el) el.textContent = state.result ? 'LIVE MAP · RESULT READY' : state.running ? 'LIVE MAP · EVENT STREAM AVAILABLE AFTER PROVIDER RESPONSE' : 'LIVE MAP · READY'; }
  function bindMap() { const canvas = $('super-map-canvas'); if (!canvas || canvas.dataset.bound) return; canvas.dataset.bound = '1'; canvas.addEventListener('wheel', event => { event.preventDefault(); state.mapScale = clamp(state.mapScale + (event.deltaY < 0 ? .1 : -.1), .55, 2.3); drawMap(); }, { passive: false }); canvas.addEventListener('pointerdown', event => { state.pointer = { x: event.clientX, y: event.clientY, panX: state.mapPanX, panY: state.mapPanY }; canvas.setPointerCapture?.(event.pointerId); }); canvas.addEventListener('pointermove', event => { if (!state.pointer) return; state.mapPanX = state.pointer.panX + event.clientX - state.pointer.x; state.mapPanY = state.pointer.panY + event.clientY - state.pointer.y; drawMap(); }); canvas.addEventListener('pointerup', () => { state.pointer = null; }); canvas.addEventListener('pointercancel', () => { state.pointer = null; }); canvas.addEventListener('dblclick', () => { state.mapScale = 1; state.mapPanX = 0; state.mapPanY = 0; drawMap(); }); }

  function bindUI() {
    loadConfig(); loadHistory();
    $('super-open-btn')?.addEventListener('click', open); $('super-close-btn')?.addEventListener('click', close); $('super-nav-btn')?.addEventListener('click', open); $('super-run-btn')?.addEventListener('click', runPipeline); $('super-pause-btn')?.addEventListener('click', pausePipeline); $('super-continue-btn')?.addEventListener('click', continuePipeline); $('super-cancel-btn')?.addEventListener('click', cancelPipeline); $('super-skip-btn')?.addEventListener('click', skipSelected); $('super-add-node')?.addEventListener('click', addNode); $('super-test-connection')?.addEventListener('click', testConnection); $('super-save-final')?.addEventListener('click', () => saveSession(false)); $('super-save-full')?.addEventListener('click', () => saveSession(true)); $('super-dont-save')?.addEventListener('click', hideConsent); $('super-replay-btn')?.addEventListener('click', replayHistory); $('super-export-svg')?.addEventListener('click', () => exportProcess('svg')); $('super-export-png')?.addEventListener('click', () => exportProcess('png')); $('super-export-text')?.addEventListener('click', () => exportProcess('txt')); $('super-history-search')?.addEventListener('input', event => { const query = event.target.value.toLowerCase(); document.querySelectorAll('#super-history-list button').forEach(button => { button.hidden = !button.textContent.toLowerCase().includes(query); }); }); $('super-map-fit')?.addEventListener('click', () => { state.mapScale = 1; state.mapPanX = 0; state.mapPanY = 0; drawMap(); }); $('super-map-zoom-in')?.addEventListener('click', () => { state.mapScale = clamp(state.mapScale + .15, .55, 2.3); drawMap(); }); $('super-map-zoom-out')?.addEventListener('click', () => { state.mapScale = clamp(state.mapScale - .15, .55, 2.3); drawMap(); }); $('super-map-reset')?.addEventListener('click', () => { state.mapScale = 1; state.mapPanX = 0; state.mapPanY = 0; drawMap(); }); bindMap(); window.addEventListener('resize', resizeMap); }

  window.CutRealSuper = { open, close, run: runPipeline, addModel: addNode, loadProviders, isOpen: () => state.open };
  document.addEventListener('DOMContentLoaded', bindUI);
})();
